### ISSUE TITLE
No output in console

### ISSUE THREAD

**Issue by jlogar** [doblak/st-copy#1]
Editing a file and saving should output "File ... copied to: ..." to console if I read the code correctly. Nothing comes up though.

Using ST 2.0.2, 2221

**Comment by doblak** [comment]
Error handling is less then perfect, I do agree. If anyone else hits the problem, debug the code a bit, once you manage to set it up, it works flawlessly.

Since I switched from NetBeans+Sublime to Intellij IDEA, I probably won't improve this script further.
